name: @name@
version: @version@
description: @description@
main: @group@.moarsms.bukkit.MoarSMSPlugin
website: https://mikroskeem.eu
authors:
- mikroskeem

commands:
  moarsms:
    description: Reload MoarSMS
    usage: /<command>
    permission-message: Nope
    permission: moarsms.moarsms

permissions:
  moarsms.moarsms:
    description: Use /moarsms command
    default: op
